general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0 # Sometimes changing the size by 0.5px fixes rendering glitches

[font.offset]
x = 0
y = -1 # Try changing this to 0, 1, or 2 to see which aligns the blocks perfectly

[font.glyph_offset]
x = 0
y = 2 # If the icons look "too high" or "too low" inside the blocks, tweak this

